// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: configuration.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteNamespaceRequest contains the namespace configuration to write
type WriteNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace configuration to write
	Config *NamespaceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Optional consistency token
	ConsistencyToken string `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	// Whether to allow updates to existing namespaces
	AllowUpdate   bool `protobuf:"varint,3,opt,name=allow_update,json=allowUpdate,proto3" json:"allow_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteNamespaceRequest) Reset() {
	*x = WriteNamespaceRequest{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNamespaceRequest) ProtoMessage() {}

func (x *WriteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*WriteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *WriteNamespaceRequest) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *WriteNamespaceRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *WriteNamespaceRequest) GetAllowUpdate() bool {
	if x != nil {
		return x.AllowUpdate
	}
	return false
}

// WriteNamespaceResponse confirms the write operation
type WriteNamespaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consistency token for subsequent operations
	ConsistencyToken string `protobuf:"bytes,1,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	// When the namespace was written
	WrittenAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	// The written namespace configuration
	Config        *NamespaceConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteNamespaceResponse) Reset() {
	*x = WriteNamespaceResponse{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNamespaceResponse) ProtoMessage() {}

func (x *WriteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*WriteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *WriteNamespaceResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *WriteNamespaceResponse) GetWrittenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

func (x *WriteNamespaceResponse) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ReadNamespaceRequest specifies which namespace to read
type ReadNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name to read
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Optional consistency token
	ConsistencyToken string `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadNamespaceRequest) Reset() {
	*x = ReadNamespaceRequest{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNamespaceRequest) ProtoMessage() {}

func (x *ReadNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNamespaceRequest.ProtoReflect.Descriptor instead.
func (*ReadNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *ReadNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReadNamespaceRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// ReadNamespaceResponse contains the namespace configuration
type ReadNamespaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace configuration
	Config *NamespaceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Consistency token
	ConsistencyToken string `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadNamespaceResponse) Reset() {
	*x = ReadNamespaceResponse{}
	mi := &file_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNamespaceResponse) ProtoMessage() {}

func (x *ReadNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNamespaceResponse.ProtoReflect.Descriptor instead.
func (*ReadNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *ReadNamespaceResponse) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ReadNamespaceResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// ListNamespacesRequest specifies filters for listing namespaces
type ListNamespacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional consistency token
	ConsistencyToken string `protobuf:"bytes,1,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	// Pagination token
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Maximum number of namespaces to return
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *ListNamespacesRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *ListNamespacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListNamespacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListNamespacesResponse contains the list of namespaces
type ListNamespacesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace configurations
	Configs []*NamespaceConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	// Token for next page of results
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Consistency token
	ConsistencyToken string `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *ListNamespacesResponse) GetConfigs() []*NamespaceConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListNamespacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListNamespacesResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// DeleteNamespaceRequest specifies which namespace to delete
type DeleteNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name to delete
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Optional consistency token
	ConsistencyToken string `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	// Whether to force delete even if tuples exist
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// DeleteNamespaceResponse confirms the delete operation
type DeleteNamespaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consistency token for subsequent operations
	ConsistencyToken string `protobuf:"bytes,1,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	// When the namespace was deleted
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNamespaceResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *DeleteNamespaceResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// ValidateNamespaceRequest contains a namespace configuration to validate
type ValidateNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace name being validated
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The namespace configuration to validate
	Config        *NamespaceConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateNamespaceRequest) Reset() {
	*x = ValidateNamespaceRequest{}
	mi := &file_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNamespaceRequest) ProtoMessage() {}

func (x *ValidateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*ValidateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ValidateNamespaceRequest) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ValidateNamespaceResponse contains validation results
type ValidateNamespaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the configuration is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Validation errors if any
	Errors []*ValidationError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Validation warnings if any
	Warnings      []*ValidationWarning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateNamespaceResponse) Reset() {
	*x = ValidateNamespaceResponse{}
	mi := &file_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNamespaceResponse) ProtoMessage() {}

func (x *ValidateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*ValidateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateNamespaceResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateNamespaceResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateNamespaceResponse) GetWarnings() []*ValidationWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// ValidationError represents a configuration validation error
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field that has an error
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// The error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The error code
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{10}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ValidationWarning represents a configuration validation warning
type ValidationWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field that has a warning
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// The warning message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The warning code
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationWarning) Reset() {
	*x = ValidationWarning{}
	mi := &file_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationWarning) ProtoMessage() {}

func (x *ValidationWarning) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationWarning.ProtoReflect.Descriptor instead.
func (*ValidationWarning) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{11}
}

func (x *ValidationWarning) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationWarning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x12\bgoacl.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vtypes.proto\"\x9a\x01\n" +
	"\x15WriteNamespaceRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.goacl.v1.NamespaceConfigR\x06config\x12+\n" +
	"\x11consistency_token\x18\x02 \x01(\tR\x10consistencyToken\x12!\n" +
	"\fallow_update\x18\x03 \x01(\bR\vallowUpdate\"\xb3\x01\n" +
	"\x16WriteNamespaceResponse\x12+\n" +
	"\x11consistency_token\x18\x01 \x01(\tR\x10consistencyToken\x129\n" +
	"\n" +
	"written_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\twrittenAt\x121\n" +
	"\x06config\x18\x03 \x01(\v2\x19.goacl.v1.NamespaceConfigR\x06config\"a\n" +
	"\x14ReadNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12+\n" +
	"\x11consistency_token\x18\x02 \x01(\tR\x10consistencyToken\"w\n" +
	"\x15ReadNamespaceResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.goacl.v1.NamespaceConfigR\x06config\x12+\n" +
	"\x11consistency_token\x18\x02 \x01(\tR\x10consistencyToken\"\x80\x01\n" +
	"\x15ListNamespacesRequest\x12+\n" +
	"\x11consistency_token\x18\x01 \x01(\tR\x10consistencyToken\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"\x16ListNamespacesResponse\x123\n" +
	"\aconfigs\x18\x01 \x03(\v2\x19.goacl.v1.NamespaceConfigR\aconfigs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12+\n" +
	"\x11consistency_token\x18\x03 \x01(\tR\x10consistencyToken\"y\n" +
	"\x16DeleteNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12+\n" +
	"\x11consistency_token\x18\x02 \x01(\tR\x10consistencyToken\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x81\x01\n" +
	"\x17DeleteNamespaceResponse\x12+\n" +
	"\x11consistency_token\x18\x01 \x01(\tR\x10consistencyToken\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"k\n" +
	"\x18ValidateNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.goacl.v1.NamespaceConfigR\x06config\"\x9d\x01\n" +
	"\x19ValidateNamespaceResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x121\n" +
	"\x06errors\x18\x02 \x03(\v2\x19.goacl.v1.ValidationErrorR\x06errors\x127\n" +
	"\bwarnings\x18\x03 \x03(\v2\x1b.goacl.v1.ValidationWarningR\bwarnings\"U\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"W\n" +
	"\x11ValidationWarning\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code2\xf4\x04\n" +
	"\x14ConfigurationService\x12n\n" +
	"\x0eWriteNamespace\x12\x1f.goacl.v1.WriteNamespaceRequest\x1a .goacl.v1.WriteNamespaceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/namespaces\x12t\n" +
	"\rReadNamespace\x12\x1e.goacl.v1.ReadNamespaceRequest\x1a\x1f.goacl.v1.ReadNamespaceResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/namespaces/{namespace}\x12k\n" +
	"\x0eListNamespaces\x12\x1f.goacl.v1.ListNamespacesRequest\x1a .goacl.v1.ListNamespacesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/namespaces\x12z\n" +
	"\x0fDeleteNamespace\x12 .goacl.v1.DeleteNamespaceRequest\x1a!.goacl.v1.DeleteNamespaceResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/namespaces/{namespace}\x12\x8c\x01\n" +
	"\x11ValidateNamespace\x12\".goacl.v1.ValidateNamespaceRequest\x1a#.goacl.v1.ValidateNamespaceResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/namespaces/{namespace}/validateB\x84\x01\n" +
	"\fcom.goacl.v1B\x12ConfigurationProtoP\x01Z\x1fgithub.com/DangVTNhan/goacl/api\xa2\x02\x03GXX\xaa\x02\bGoacl.V1\xca\x02\bGoacl\\V1\xe2\x02\x14Goacl\\V1\\GPBMetadata\xea\x02\tGoacl::V1b\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_configuration_proto_goTypes = []any{
	(*WriteNamespaceRequest)(nil),     // 0: goacl.v1.WriteNamespaceRequest
	(*WriteNamespaceResponse)(nil),    // 1: goacl.v1.WriteNamespaceResponse
	(*ReadNamespaceRequest)(nil),      // 2: goacl.v1.ReadNamespaceRequest
	(*ReadNamespaceResponse)(nil),     // 3: goacl.v1.ReadNamespaceResponse
	(*ListNamespacesRequest)(nil),     // 4: goacl.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),    // 5: goacl.v1.ListNamespacesResponse
	(*DeleteNamespaceRequest)(nil),    // 6: goacl.v1.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil),   // 7: goacl.v1.DeleteNamespaceResponse
	(*ValidateNamespaceRequest)(nil),  // 8: goacl.v1.ValidateNamespaceRequest
	(*ValidateNamespaceResponse)(nil), // 9: goacl.v1.ValidateNamespaceResponse
	(*ValidationError)(nil),           // 10: goacl.v1.ValidationError
	(*ValidationWarning)(nil),         // 11: goacl.v1.ValidationWarning
	(*NamespaceConfig)(nil),           // 12: goacl.v1.NamespaceConfig
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_configuration_proto_depIdxs = []int32{
	12, // 0: goacl.v1.WriteNamespaceRequest.config:type_name -> goacl.v1.NamespaceConfig
	13, // 1: goacl.v1.WriteNamespaceResponse.written_at:type_name -> google.protobuf.Timestamp
	12, // 2: goacl.v1.WriteNamespaceResponse.config:type_name -> goacl.v1.NamespaceConfig
	12, // 3: goacl.v1.ReadNamespaceResponse.config:type_name -> goacl.v1.NamespaceConfig
	12, // 4: goacl.v1.ListNamespacesResponse.configs:type_name -> goacl.v1.NamespaceConfig
	13, // 5: goacl.v1.DeleteNamespaceResponse.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 6: goacl.v1.ValidateNamespaceRequest.config:type_name -> goacl.v1.NamespaceConfig
	10, // 7: goacl.v1.ValidateNamespaceResponse.errors:type_name -> goacl.v1.ValidationError
	11, // 8: goacl.v1.ValidateNamespaceResponse.warnings:type_name -> goacl.v1.ValidationWarning
	0,  // 9: goacl.v1.ConfigurationService.WriteNamespace:input_type -> goacl.v1.WriteNamespaceRequest
	2,  // 10: goacl.v1.ConfigurationService.ReadNamespace:input_type -> goacl.v1.ReadNamespaceRequest
	4,  // 11: goacl.v1.ConfigurationService.ListNamespaces:input_type -> goacl.v1.ListNamespacesRequest
	6,  // 12: goacl.v1.ConfigurationService.DeleteNamespace:input_type -> goacl.v1.DeleteNamespaceRequest
	8,  // 13: goacl.v1.ConfigurationService.ValidateNamespace:input_type -> goacl.v1.ValidateNamespaceRequest
	1,  // 14: goacl.v1.ConfigurationService.WriteNamespace:output_type -> goacl.v1.WriteNamespaceResponse
	3,  // 15: goacl.v1.ConfigurationService.ReadNamespace:output_type -> goacl.v1.ReadNamespaceResponse
	5,  // 16: goacl.v1.ConfigurationService.ListNamespaces:output_type -> goacl.v1.ListNamespacesResponse
	7,  // 17: goacl.v1.ConfigurationService.DeleteNamespace:output_type -> goacl.v1.DeleteNamespaceResponse
	9,  // 18: goacl.v1.ConfigurationService.ValidateNamespace:output_type -> goacl.v1.ValidateNamespaceResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
